services:
  db:
    image: postgres
    container_name: jkpg-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jkpg
    ports:
      - "5432:5432"
